# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form, dataset):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setFixedSize(450, 322)

        self.dataset = dataset

        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 381, 91))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(100, 67, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 171, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_Hipotez = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_Hipotez.setObjectName(_fromUtf8("groupBox_Hipotez"))
        self.radio_greater = QtGui.QRadioButton(self.groupBox_Hipotez)
        self.radio_greater.setEnabled(True)
        self.radio_greater.setGeometry(QtCore.QRect(10, 80, 151, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_greater.sizePolicy().hasHeightForWidth())
        self.radio_greater.setSizePolicy(sizePolicy)
        self.radio_greater.setObjectName(_fromUtf8("radio_greater"))
        self.radio_noteq = QtGui.QRadioButton(self.groupBox_Hipotez)
        self.radio_noteq.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.radio_noteq.setChecked(True)
        self.radio_noteq.setObjectName(_fromUtf8("radio_noteq"))
        self.radio_less = QtGui.QRadioButton(self.groupBox_Hipotez)
        self.radio_less.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.radio_less.setObjectName(_fromUtf8("radio_less"))
        self.verticalLayout.addWidget(self.groupBox_Hipotez)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 90, 211, 111))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_TestType = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_TestType.setObjectName(_fromUtf8("groupBox_TestType"))
        self.radioExact = QtGui.QRadioButton(self.groupBox_TestType)
        self.radioExact.setGeometry(QtCore.QRect(10, 80, 256, 17))
        self.radioExact.setObjectName(_fromUtf8("radioExact"))
        self.radioNormalCorrection = QtGui.QRadioButton(self.groupBox_TestType)
        self.radioNormalCorrection.setGeometry(QtCore.QRect(10, 50, 191, 21))
        self.radioNormalCorrection.setObjectName(_fromUtf8("radioNormalCorrection"))
        self.radioNormal = QtGui.QRadioButton(self.groupBox_TestType)
        self.radioNormal.setGeometry(QtCore.QRect(10, 20, 256, 17))
        self.radioNormal.setChecked(True)
        self.radioNormal.setObjectName(_fromUtf8("radioNormal"))
        self.verticalLayout_2.addWidget(self.groupBox_TestType)
        self.layoutWidget_4 = QtGui.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 200, 381, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.h0_edit = QtGui.QLineEdit(self.layoutWidget_4)
        self.h0_edit.setObjectName(_fromUtf8("h0_edit"))
        self.horizontalLayout.addWidget(self.h0_edit)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 270, 271, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnTemizle = QtGui.QPushButton(self.layoutWidget)
        self.btnTemizle.setObjectName(_fromUtf8("btnTemizle"))
        self.horizontalLayout_4.addWidget(self.btnTemizle)
        self.btnTamam = QtGui.QPushButton(self.layoutWidget)
        self.btnTamam.setObjectName(_fromUtf8("btnTamam"))
        self.horizontalLayout_4.addWidget(self.btnTamam)
        self.btnYardim = QtGui.QPushButton(self.layoutWidget)
        self.btnYardim.setObjectName(_fromUtf8("btnYardim"))
        self.horizontalLayout_4.addWidget(self.btnYardim)
        self.layoutWidget_5 = QtGui.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 230, 381, 41))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.h0_edit_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.h0_edit_2.setObjectName(_fromUtf8("h0_edit_2"))
        self.horizontalLayout_5.addWidget(self.h0_edit_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_6.setText(_translate("Form", "Grup Seçiniz", None))
        self.groupBox_Hipotez.setTitle(_translate("Form", "Alternatif Hipotez", None))
        self.radio_greater.setText(_translate("Form", "Population proportion > p0", None))
        self.radio_noteq.setText(_translate("Form", "Population proportion != p0", None))
        self.radio_less.setText(_translate("Form", "Population proportion < p0", None))
        self.groupBox_TestType.setTitle(_translate("Form", "Test Tipi", None))
        self.radioExact.setText(_translate("Form", "Exact binomial", None))
        self.radioNormalCorrection.setText(_translate("Form", "Normal Approximation with \n"
"continuity correction", None))
        self.radioNormal.setText(_translate("Form", "Normal Approximation", None))
        self.label_2.setText(_translate("Form", "   Null Hipotez : p        ", None))
        self.h0_edit.setText(_translate("Form", "0.5", None))
        self.btnTemizle.setText(_translate("Form", "Temizle", None))
        self.btnTamam.setText(_translate("Form", "Tamam", None))
        self.btnYardim.setText(_translate("Form", "Yardım", None))
        self.label_3.setText(_translate("Form", "   Güven Aralığı           ", None))
        self.h0_edit_2.setText(_translate("Form", "0.05", None))

