# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form, dataset):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setFixedSize(450, 342)

        self.dataset = dataset

        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 381, 91))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(100, 67, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 310, 271, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnTemizle = QtGui.QPushButton(self.layoutWidget)
        self.btnTemizle.setObjectName(_fromUtf8("btnTemizle"))
        self.horizontalLayout_4.addWidget(self.btnTemizle)
        self.btnTamam = QtGui.QPushButton(self.layoutWidget)
        self.btnTamam.setObjectName(_fromUtf8("btnTamam"))
        self.horizontalLayout_4.addWidget(self.btnTamam)
        self.btnYardim = QtGui.QPushButton(self.layoutWidget)
        self.btnYardim.setObjectName(_fromUtf8("btnYardim"))
        self.horizontalLayout_4.addWidget(self.btnYardim)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 381, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setSpacing(40)
        self.horizontalLayout_6.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.comboBox_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        spacerItem1 = QtGui.QSpacerItem(100, 67, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.layoutWidget_2 = QtGui.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 160, 109, 111))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setSpacing(14)
        self.verticalLayout_6.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radio_greater_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radio_greater_3.setEnabled(True)
        self.radio_greater_3.setGeometry(QtCore.QRect(10, 78, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_greater_3.sizePolicy().hasHeightForWidth())
        self.radio_greater_3.setSizePolicy(sizePolicy)
        self.radio_greater_3.setObjectName(_fromUtf8("radio_greater_3"))
        self.radio_noteq_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radio_noteq_3.setGeometry(QtCore.QRect(10, 20, 100, 16))
        self.radio_noteq_3.setChecked(True)
        self.radio_noteq_3.setObjectName(_fromUtf8("radio_noteq_3"))
        self.radio_less_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radio_less_3.setGeometry(QtCore.QRect(10, 47, 100, 16))
        self.radio_less_3.setObjectName(_fromUtf8("radio_less_3"))
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 160, 211, 111))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_TestType_2 = QtGui.QGroupBox(self.verticalLayoutWidget_3)
        self.groupBox_TestType_2.setObjectName(_fromUtf8("groupBox_TestType_2"))
        self.radioNormalCorrection_2 = QtGui.QRadioButton(self.groupBox_TestType_2)
        self.radioNormalCorrection_2.setGeometry(QtCore.QRect(10, 60, 191, 21))
        self.radioNormalCorrection_2.setObjectName(_fromUtf8("radioNormalCorrection_2"))
        self.radioNormal_2 = QtGui.QRadioButton(self.groupBox_TestType_2)
        self.radioNormal_2.setGeometry(QtCore.QRect(10, 30, 256, 17))
        self.radioNormal_2.setChecked(True)
        self.radioNormal_2.setObjectName(_fromUtf8("radioNormal_2"))
        self.verticalLayout_7.addWidget(self.groupBox_TestType_2)
        self.layoutWidget_6 = QtGui.QWidget(Form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(50, 270, 321, 41))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.h0_edit_3 = QtGui.QLineEdit(self.layoutWidget_6)
        self.h0_edit_3.setObjectName(_fromUtf8("h0_edit_3"))
        self.horizontalLayout_8.addWidget(self.h0_edit_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_6.setText(_translate("Form", "Grup Seçiniz            ", None))
        self.btnTemizle.setText(_translate("Form", "Temizle", None))
        self.btnTamam.setText(_translate("Form", "Tamam", None))
        self.btnYardim.setText(_translate("Form", "Yardım", None))
        self.label_7.setText(_translate("Form", "Response Değişkeni", None))
        self.groupBox_2.setTitle(_translate("Form", "Alternatif Hipotez", None))
        self.radio_greater_3.setText(_translate("Form", "Fark > 0", None))
        self.radio_noteq_3.setText(_translate("Form", "İki taraflı", None))
        self.radio_less_3.setText(_translate("Form", "Fark < 0", None))
        self.groupBox_TestType_2.setTitle(_translate("Form", "Test Tipi", None))
        self.radioNormalCorrection_2.setText(_translate("Form", "Normal Approximation with \n"
"continuity correction", None))
        self.radioNormal_2.setText(_translate("Form", "Normal Approximation", None))
        self.label_4.setText(_translate("Form", "   Güven Aralığı           ", None))
        self.h0_edit_3.setText(_translate("Form", "0.05", None))

